# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
#  sonarqube: onehq/sonarqube@0.3.0

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.3

    steps: 
      - checkout

      - run:
          name: Setup testing environment
          command: pipenv install

      - run:
          name: Run tests
          command: |
            export PYTHONPATH="$PWD"
            pipenv run coverage run tests/test_math_functions.py

      - codecov/upload:
          file: coverage.yml
#      - run:
#          name: Check code coverage
#          command: |
#            export CODECOV_TOKEN="741159c4-9c75-4a66-90c1-76af59143255"
#            pipenv run codecov

workflows:
  version: 2.1
  workflow:
    jobs:
    - build