# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.3

    steps:
      - checkout

      - run:
          name: Setup testing environment
          command: pipenv install

      - run:
          name: Run tests
          command: |
            $HOME/.local/bin/coverage run test_math_functions.py
            $HOME/.local/bin/coverage report
            $HOME/.local/bin/coverage html

      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  workflow:
    jobs:
      - build